# Generated by Django 4.0.2 on 2022-02-26 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_employee_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='correctaccess',
            name='time_out_days',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='manager_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ManagerDepartments',
        ),
    ]
