# Generated by Django 4.0.2 on 2022-02-27 18:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0010_alter_timekeeper_timecheck'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timekeeper',
            name='timecheck',
        ),
        migrations.AddField(
            model_name='timekeeper',
            name='time_check',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
