# Generated by Django 4.0.2 on 2022-02-27 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0011_remove_timekeeper_timecheck_timekeeper_time_check'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timekeeper',
            old_name='time_check',
            new_name='timecheck',
        ),
    ]
