# Generated by Django 4.0.2 on 2022-02-27 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0012_rename_time_check_timekeeper_timecheck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timekeeper',
            name='timecheck',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
