# Generated by Django 3.2.12 on 2022-03-01 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0013_alter_timekeeper_timecheck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timekeeper',
            name='timecheck',
            field=models.DateTimeField(),
        ),
    ]
