# Generated by Django 3.2.12 on 2022-03-01 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0014_alter_timekeeper_timecheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='correctaccess',
            name='is_approval',
            field=models.BooleanField(default=False),
        ),
    ]
