# Generated by Django 3.2.12 on 2022-03-01 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0015_correctaccess_is_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correctaccess',
            name='time_in_days',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='correctaccess',
            name='time_out_days',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
