# Generated by Django 3.2.12 on 2022-03-01 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0017_auto_20220301_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approver', to='hr.employee'),
        ),
    ]
