# Generated by Django 3.2.12 on 2022-03-03 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0018_alter_approval_approver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
